### ISSUE TITLE
[BUG] Crashed when spamming directory list

### ISSUE THREAD

**Issue by MDP43140** [FoedusProgramme/Gramophone#140]
**Describe the bug**
The bug happened when the user spam clicked on ".." folder in Filesystem tab,
this seems to be caused by an unhandled empty/null list...

**To Reproduce**
1. Open the app
2. Go to "Filesystem"
3. Open a folder
4. Now spam click on ".."
5. And crashed...

**Expected behavior**
It should be able to handle such condition

**Screenshots**

https://github.com/AkaneTan/Gramophone/assets/68391650/92b1dea8-bb45-46be-9f90-bdaba56ab59d

**Device:**
 - Device: Samsung SM-A600G
 - OS: Android 10, OneUi 2.0
 - App Version: 1.0.4.1.9cd07e

**Additional context**
--------- beginning of crash
java.util.NoSuchElementException: List is empty.
	at z3.E.x(SourceFile:49)
	at com.google.android.material.datepicker.l.onClick(SourceFile:112)
	at android.view.View.performClick(View.java:7862)
	at android.view.View.performClickInternal(View.java:7831)
	at android.view.View.access$3600(View.java:879)
	at android.view.View$PerformClick.run(View.java:29359)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by nift4** [comment]
Should be fixed these days
