### ISSUE TITLE
[BUG] Foreground exception

### ISSUE THREAD

**Issue by lschierer** [FoedusProgramme/Gramophone#204]
**Describe the bug**
Crash report waking the app in the morning 

**To Reproduce**

**Expected behavior**
Gramophone should wake and come to the foreground normally 

**Screenshots**

**Smartphone (please complete the following information):**
 -Gramophone version: 1.0.8.04a37e

Brand:     samsung
Model:     SM-T860
SDK Level: 32

**Additional context**

Thread:    main

Time: 2024-06-10 08:28:23
--------- beginning of crash
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f5d3f57 u0 org.akanework.gramophone/.logic.GramophonePlaybackService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2206)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2177)
	at android.app.ActivityThread.access$3000(ActivityThread.java:324)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8855)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by nift4** [comment]
did this ever happen again?

**Comment by lschierer** [comment]
I've had a few more crashes, but not frequently.

**Comment by nift4** [comment]
This unfortunately appears to be something we can't really fix because it seems to happen on Android 12 only, sorry.

**Comment by nift4** [comment]
From Google's side there have been a few more bug fixes, did you ever have this again?
If you did, I can add a workaround that just skips the crash reporter for these.

**Comment by lschierer** [comment]
Lately I haven't seen it crash.  Several times I have needed to force stop it and clean the cache because it hangs on this blank black screen bringing it to the fore, but I don't see a pattern for when or why.  It isn't frequent.

**Comment by nift4** [comment]
that blank screen bug is already fixed in the dev version and I'm pushing out a release soon, that was quite the blunder that led to this bug.
closing this issue as crash wasn't observed.
