### ISSUE TITLE
[BUG] invalid component name media button retriever

### ISSUE THREAD

**Issue by nift4** [FoedusProgramme/Gramophone#208]
Gramophone version: 1.0.7.9bbf79

Brand:     motorola
Model:     motorola edge 40
SDK Level: 34
Thread:    main

Time: 2024-06-10 09:46:01
--------- beginning of crash
java.lang.RuntimeException: Unable to create service org.akanework.gramophone.logic.GramophonePlaybackService: java.lang.IllegalArgumentException: Invalid component name: ComponentInfo{org.akanework.gramophone/androidx.media3.session.MediaButtonReceiver}
 at android.app.ActivityThread.handleCreateService(ActivityThread.java:4808)
 at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2388)
 at android.os.Handler.dispatchMessage(Handler.java:111)
 at android.os.Looper.loopOnce(Looper.java:242)
 at android.os.Looper.loop(Looper.java:362)
 at android.app.ActivityThread.main(ActivityThread.java:8448)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: java.lang.IllegalArgumentException: Invalid component name: ComponentInfo{org.akanework.gramophone/androidx.media3.session.MediaButtonReceiver}
 at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
 at android.os.Parcel.createException(Parcel.java:3041)
 at android.os.Parcel.readException(Parcel.java:3024)
 at android.os.Parcel.readException(Parcel.java:2966)
 at android.media.session.ISession$Stub$Proxy.setMediaButtonBroadcastReceiver(ISession.java:478)
 at android.media.session.MediaSession.setMediaButtonBroadcastReceiver(MediaSession.java:321)
 at androidx.media3.session.MediaSession$Api31$$ExternalSyntheticApiModelOutline0.m(SourceFile:3)
 at androidx.media3.session.MediaSessionLegacyStub$Api31.setMediaButtonBroadcastReceiver(SourceFile:5)
 at androidx.media3.session.MediaSessionLegacyStub.<init>(SourceFile:281)
 at androidx.media3.session.MediaLibrarySessionImpl.<init>(SourceFile:164)
 at androidx.media3.session.MediaSession.<init>(SourceFile:44)
 at org.akanework.gramophone.logic.GramophonePlaybackService.onCreate(SourceFile:571)
 at android.app.ActivityThread.handleCreateService(ActivityThread.java:4795)
 ... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
 at com.android.server.media.MediaSessionRecord$SessionStub.setMediaButtonBroadcastReceiver(MediaSessionRecord.java:1102)
 at android.media.session.ISession$Stub.onTransact(ISession.java:258)
 at android.os.Binder.execTransactInternal(Binder.java:1380)
 at android.os.Binder.execTransact(Binder.java:1310)

**Comment by nift4** [comment]
It seems like this crash is caused by Gramophone being set to "Don't allow" in Settings - Battery - Manage background apps. 
The next media3 release includes a fix for the crash, hence closing
