### ISSUE TITLE
[BUG] Crash report

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#210]
**Describe the bug**
Gramophone crashed randomly, no specific steps or actions are given.

**Report source**
Telegram group by pcocphone

**Smartphone:**
 - Device: Amazon
 - OS: Fire OS 8.3.2.4
 - App Version: 1.0.8.04a37e

**Logs**

```
Gramophone version: 1.0.8.04a37e

Brand:     Amazon
Model:     KFRAWI
SDK Level: 30
Thread:    main


Time: 2024-06-23 16:55:11
--------- beginning of crash
java.lang.IllegalStateException: valueFrom(0.0) must be smaller than valueTo(0.0)
 at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(SourceFile:520)
 at com.google.android.material.slider.BaseSlider.onDraw(SourceFile:9)
 at android.view.View.draw(View.java:22350)
 at android.view.View.updateDisplayListIfDirty(View.java:21226)
 at android.view.View.draw(View.java:22081)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
 at android.view.View.updateDisplayListIfDirty(View.java:21217)
 at android.view.View.draw(View.java:22081)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
 at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(SourceFile:29)
 at android.view.View.updateDisplayListIfDirty(View.java:21217)
 at android.view.View.draw(View.java:22081)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
 at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(SourceFile:29)
 at android.view.View.draw(View.java:22353)
 at android.view.View.updateDisplayListIfDirty(View.java:21226)
 at android.view.View.draw(View.java:22081)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
 at android.view.View.draw(View.java:22353)
 at android.view.View.updateDisplayListIfDirty(View.java:21226)
 at android.view.View.draw(View.java:22081)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
 at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(SourceFile:14)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
 at android.view.View.updateDisplayListIfDirty(View.java:21217)
 at android.view.View.draw(View.java:22081)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
 at android.view.View.updateDisplayListIfDirty(View.java:21217)
 at android.view.View.draw(View.java:22081)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
 at android.view.View.updateDisplayListIfDirty(View.java:21217)
 at android.view.View.draw(View.java:22081)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
 at android.view.View.updateDisplayListIfDirty(View.java:21217)
 at android.view.View.draw(View.java:22081)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
 at android.view.View.updateDisplayListIfDirty(View.java:21217)
 at android.view.View.draw(View.java:22081)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
 at android.view.View.draw(View.java:22353)
 at com.android.internal.policy.DecorView.draw(DecorView.java:816)
 at android.view.View.updateDisplayListIfDirty(View.java:21226)
 at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
 at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
 at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
 at android.view.ViewRootImpl.draw(ViewRootImpl.java:4120)
 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3847)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3118)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1968)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8200)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:995)
 at android.view.Choreographer.doCallbacks(Choreographer.java:818)
 at android.view.Choreographer.doFrame(Choreographer.java:752)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:980)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7719)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by perrsona1234** [comment]
**Describe the bug:**

Gramophone has also crashed for me randomly today. I left the song paused yesterday and today I re-opened the app and it crashed.

**Report source:**

My own.

**Smartphone:**

Device: Motorola Moto E7 Power
OS: Official Android 10 from Motorola
App Version: 1.0.8.04a37e

**Logs:**

```
Gramophone version: 1.0.8.04a37e

Brand:     motorola
Model:     moto e(7) power
SDK Level: 29
Thread:    main


Time: 2024-07-26 09:51:10
--------- beginning of crash
androidx.startup.StartupException: lateinit property recyclerView has not been initialized
	at org.akanework.gramophone.ui.fragments.ArtistSubFragment.onDestroyView(SourceFile:25)
	at androidx.fragment.app.FragmentStateManager.destroyFragmentView(SourceFile:65)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:234)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(SourceFile:1203)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(SourceFile:82)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(SourceFile:78)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(SourceFile:67)
	at androidx.appcompat.app.AppCompatActivity.onStart$androidx$fragment$app$FragmentActivity(SourceFile:34)
	at androidx.appcompat.app.AppCompatActivity.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
	at android.app.Activity.performStart(Activity.java:7825)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3322)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

**Comment by nift4** [comment]
I think these bugs are fixed now, if not, please reopen with a new report
