### ISSUE TITLE
[BUG] Crash on switching to app

### ISSUE THREAD

**Issue by AaronM04** [FoedusProgramme/Gramophone#275]
**Describe the bug**
I hadn't used Gramophone in a while. I switched back to it and saw this stacktrace. Doing the back button caused it to appear again. This can be repeated with same effect. Swiping the app away and coming back to it temporarily fixed the issue.

**To Reproduce**
1. As described above

**Expected behavior**
No stacktrace

**Screenshots**
See stacktrace

**Smartphone (please complete the following information):**
Gramophone version: 1.0.11.0fc896

Brand:     google
Model:     Pixel 7a
SDK Level: 34
Thread:    main

Time: 2024-09-28 15:54:51
```
--------- beginning of crash
androidx.startup.StartupException: lateinit property recyclerView has not been initialized
at org.akanework.gramophone.ui.fragments.ArtistSubFragment.onDestroyView(SourceFile:25)
at androidx.fragment.app.FragmentStateManager.destroyFragmentView(SourceFile:65)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:234)
at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(SourceFile:1213)
at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(SourceFile:82)
at androidx.fragment.app.FragmentManagerImpl.execPendingActions(SourceFile:78)
at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(SourceFile:67)
at androidx.appcompat.app.AppCompatActivity.onStart$androidx$fragment$app$FragmentActivity(SourceFile:34)
at androidx.appcompat.app.AppCompatActivity.onStart(SourceFile:1)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1706)
at android.app.Activity.performStart(Activity.java:9056)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4029)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:327)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8623)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
at com.android.internal.os.ExecInit.main(ExecInit.java:50)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

- [x] I will follow the issue format and will add `[BUG]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by AaronM04** [comment]
Previously described here: https://github.com/AkaneTan/Gramophone/issues/210#issuecomment-2252187437

However, it is not fixed with the later version.

**Comment by nift4** [comment]
This should be fixed in the next release, if not, please send a new crash report. Thanks!
