### ISSUE TITLE
[BUG] Crash with Playlist button

### ISSUE THREAD

**Issue by Joshua-Mastachi** [FoedusProgramme/Gramophone#278]
**Describe the bug**
Pressing the Playlist button on currently playing panel causes crash

**To Reproduce**
1. Start playing an audio
2. Press the currently playing bar (bottom of the screen)
3. Press the Playlist button (bottom right, last button)
4. See crash

**Expected behavior**
See the list of next audio files in the cue.

**Screenshots**
![Screenshot_20241001_222847](https://github.com/user-attachments/assets/5dd69e02-58ee-4d70-ad23-04182cc766dc)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 10+
 - OS: Android 12
 - App Version: 1.0.12 (F-Droid)

**Additional context**
Crash log:

```
Gramophone version: 1.0.12.42ed78

Brand:     samsung
Model:     SM-N975U
SDK Level: 31
Thread:    main


Time: 2024-10-01 22:17:16
--------- beginning of crash
java.lang.NullPointerException
	at org.akanework.gramophone.ui.components.FullBottomSheet$PlaylistCardAdapter.onBindViewHolder(SourceFile:54)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(SourceFile:147)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:1183)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(SourceFile:63)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:49)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:808)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:74)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(SourceFile:64)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.view.View.measure(View.java:27129)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.onMeasureChild(SourceFile:54)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(SourceFile:387)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:160)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1277)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4536)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3228)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3533)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

- [x] I will follow the issue format and will add `[BUG]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by nift4** [comment]
This should be fixed in the next release, if not, please send a new crash report. Thanks!
