### ISSUE TITLE
[BUG] When tried to open m3u8 playlist file from file manager using “open with“

### ISSUE THREAD

**Issue by lamyergeier** [FoedusProgramme/Gramophone#350]
**Describe the bug**

Gramophone version: 1.0.15.64ab51

Brand:     samsung
Model:     SM-A336B
SDK Level: 34
Thread:    main

Time: 2024-12-18 23:52:27
--------- beginning of crash
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.akanework.gramophone/org.akanework.gramophone.ui.AudioPreviewActivity}: java.lang.IllegalStateException: No suitable media source factory found for content type: 2
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.IllegalStateException: No suitable media source factory found for content type: 2
	at org.akanework.gramophone.logic.utils.exoplayer.GramophoneMediaSourceFactory.createMediaSource(SourceFile:909)
	at androidx.media3.exoplayer.ExoPlayerImpl.createMediaSources(SourceFile:21)
	at androidx.media3.exoplayer.ExoPlayerImpl.setMediaItems$1(SourceFile:4)
	at org.akanework.gramophone.ui.AudioPreviewActivity.handleIntent(SourceFile:34)
	at org.akanework.gramophone.ui.AudioPreviewActivity.onCreate(SourceFile:445)
	at android.app.Activity.performCreate(Activity.java:8975)
	at android.app.Activity.performCreate(Activity.java:8944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
	... 12 more

**To Reproduce**
1. Go to Amaze Gile browser
2. Click on a playlist file 
3. Click Open with gramophone 

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]Samsung A33
 - OS: [e.g. iOS8.1]Android 14
 - App Version: [e.g. 22]latest from fdroid 

**Additional context**

- [x] I will open one issue per bug, follow the issue format and will add `[BUG]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by nift4** [comment]
Thanks, fixed. Fix will be available in next release

**Comment by lamyergeier** [comment]
@nift4  With latest release, I get this message on Samsung A33 (Android 14)

```
Cannot play this file
```

While vlc plays the playlist.

**Comment by nift4** [comment]
I fixed the crash by catching unsupported file types to show that message.

If you want to play playlists from a file manager, I'm not sure how easy or hard that'd be, but there's a ticket for doing something with playlists when clicked: #178
