### ISSUE TITLE
[BUG] Crash on app switching, or phone direction change

### ISSUE THREAD

**Issue by Porkepix** [FoedusProgramme/Gramophone#53]
**Describe the bug**
Can't reproduce reliably currently nor am I sure this happened when switching to landscape/portrait or just coming back to Gramophone from something else, but it ended up totally crashed

**Expected behavior**
No crash

**Logs from `adb logcat` and Screenshot from exception from within application**
```
12-03 16:58:41.903  7854  7854 E AndroidRuntime: FATAL EXCEPTION: main
12-03 16:58:41.903  7854  7854 E AndroidRuntime: Process: org.akanework.gramophone, PID: 7854
12-03 16:58:41.903  7854  7854 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {org.akanework.gramophone/org.akanework.gramophone.ui.MainActivity}: java.util.concurrent.CancellationException: Task was cancelled.
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3650)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3690)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:251)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6572)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: Caused by: java.util.concurrent.CancellationException: Task was cancelled.
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at j6.l.g(SourceFile:33)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at j6.l.get(Unknown Source:21)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at org.akanework.gramophone.ui.components.PlayerBottomSheet.setVisible(SourceFile:28)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at o7.a.B(SourceFile:1)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at android.support.v4.media.k.Q(SourceFile:51)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at d1.e1.q(SourceFile:70)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at d1.e1.k(SourceFile:58)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at d1.y0.N(SourceFile:62)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at d1.y0.u(SourceFile:36)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at d1.i0.onStart(SourceFile:68)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at h.o.onStart(SourceFile:1)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6992)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at android.app.Activity.performRestart(Activity.java:7066)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7071)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3625)
12-03 16:58:41.903  7854  7854 E AndroidRuntime: 	... 8 more
12-03 16:58:41.976  1373  1438 W ActivityManager: setHasOverlayUi called on unknown pid: 785
```

<details>
<summary>
Screenshots
</summary>

![Screenshot_20231203-165903](https://github.com/AkaneTan/Gramophone/assets/709500/1407011b-7405-4477-8f1a-dd9201d9cdb1)
![Screenshot_20231203-165907](https://github.com/AkaneTan/Gramophone/assets/709500/16f0625d-62da-42ed-b5c0-5ead6bc73a7c)

</details>

**Smartphone (please complete the following information):**
 - Device: Xperia XZ
 - OS: Android Oreo 8.0
 - Release from https://github.com/AkaneTan/Gramophone/issues/37#issuecomment-1837493118

**Comment by nift4** [comment]
https://github.com/AkaneTan/Gramophone/files/13539640/Gramophone-1.0.2.312f69-release.apk.zip
