### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by Sureshgorai25** [FoedusProgramme/Gramophone#98]
The app is crashing after opening it after few hours
See the crash log here 

Gramophone version: 1.0.4.1.9cd07e

Brand:     motorola
Model:     moto g54 5G
SDK Level: 34

Time: 2024-02-23 11:52:57

--------- beginning of crash
java.lang.RuntimeException: Unable to create service org.akanework.gramophone.logic.GramophonePlaybackService: java.lang.IllegalArgumentException: Invalid component name: ComponentInfo{org.akanework.gramophone/androidx.media3.session.MediaButtonReceiver}
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4787)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2368)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:242)
	at android.os.Looper.loop(Looper.java:362)
	at android.app.ActivityThread.main(ActivityThread.java:8393)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: java.lang.IllegalArgumentException: Invalid component name: ComponentInfo{org.akanework.gramophone/androidx.media3.session.MediaButtonReceiver}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.media.session.ISession$Stub$Proxy.setMediaButtonBroadcastReceiver(ISession.java:478)
	at android.media.session.MediaSession.setMediaButtonBroadcastReceiver(MediaSession.java:321)
	at O.c.q(SourceFile:1)
	at m1.p1.a(SourceFile:5)
	at m1.u1.<init>(SourceFile:280)
	at m1.i1.<init>(SourceFile:29)
	at m1.J0.<init>(SourceFile:1)
	at m1.X0.<init>(SourceFile:55)
	at org.akanework.gramophone.logic.GramophonePlaybackService.onCreate(SourceFile:382)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4774)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.media.MediaSessionRecord$SessionStub.setMediaButtonBroadcastReceiver(MediaSessionRecord.java:1102)
	at android.media.session.ISession$Stub.onTransact(ISession.java:258)
	at android.os.Binder.execTransactInternal(Binder.java:1359)
	at android.os.Binder.execTransact(Binder.java:1284)

**Comment by AkaneTan** [comment]
Seems like your OEM system had issues with media3, there's nothing we can do about it.

**Comment by nift4** [comment]
Please do let us know if this ever happens again, thanks

**Comment by Sureshgorai25** [comment]
> Please do let us know if this ever happens again, thanks

Sure

**Comment by Sureshgorai25** [comment]
It happened again today
Gramophone version: 1.0.4.1.9cd07e

Brand:     motorola
Model:     moto g54 5G
SDK Level: 34

Time: 2024-03-04 15:32:33

--------- beginning of crash
java.lang.RuntimeException: Unable to create service org.akanework.gramophone.logic.GramophonePlaybackService: java.lang.IllegalArgumentException: Invalid component name: ComponentInfo{org.akanework.gramophone/androidx.media3.session.MediaButtonReceiver}
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4787)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2368)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:242)
	at android.os.Looper.loop(Looper.java:362)
	at android.app.ActivityThread.main(ActivityThread.java:8393)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: java.lang.IllegalArgumentException: Invalid component name: ComponentInfo{org.akanework.gramophone/androidx.media3.session.MediaButtonReceiver}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.media.session.ISession$Stub$Proxy.setMediaButtonBroadcastReceiver(ISession.java:478)
	at android.media.session.MediaSession.setMediaButtonBroadcastReceiver(MediaSession.java:321)
	at O.c.q(SourceFile:1)
	at m1.p1.a(SourceFile:5)
	at m1.u1.<init>(SourceFile:280)
	at m1.i1.<init>(SourceFile:29)
	at m1.J0.<init>(SourceFile:1)
	at m1.X0.<init>(SourceFile:55)
	at org.akanework.gramophone.logic.GramophonePlaybackService.onCreate(SourceFile:382)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4774)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.media.MediaSessionRecord$SessionStub.setMediaButtonBroadcastReceiver(MediaSessionRecord.java:1102)
	at android.media.session.ISession$Stub.onTransact(ISession.java:258)
	at android.os.Binder.execTransactInternal(Binder.java:1359)
	at android.os.Binder.execTransact(Binder.java:1284)

![Screenshot_20240304-153250](https://github.com/AkaneTan/Gramophone/assets/93507842/ebed19ca-5ecc-402f-a759-a8aad23ed6be)

**Comment by nift4** [comment]
Hi,

I know I'm a couple months late but Google has contacted Motorola and it seems like this crash is caused by Gramophone being set to "Don't allow" in Settings - Battery - Manage background apps.

**Comment by Sureshgorai25** [comment]
Hello, things are changed now.
I don't use stock ROM provided by Motorola anymore.
I switched to custom ROM few months ago and things are going great. I haven't faced that crash issue since then.
Thanks for your reply
❤️
